chnages deploy frontend

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -169,7 +169,8 @@ jobs:
           fingerprints: ["4e:27:4b:b1:89:2e:f2:9a:22:b2:2b:8e:db:39:e8:ab"]
       # attach workspace
       - attach_workspace:
-          at: .circleci/ansible/
+          at: .
+        # at: .circleci/ansible/ - i thik it should be '.'
       - run:
           name: Install dependencies
           command: |
@@ -177,12 +178,102 @@ jobs:
             apk add --update ansible
           #exit 1
       - run:
-          name: Configure server  ##cd .circleci/ansible
+          name: Configure server  
           command: |
             cd .circleci/ansible
             ansible-playbook -i inventory.txt configure-server.yml -vvv
           #  exit 1
       # Here's where you will add some code to rollback on failure      
+      - destroy-environment:
+          stackname: "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}"
+      - destroy-environment:
+          stackname: "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}"
+
+  run-migrations:
+    docker:
+      - image: circleci/node:14.18.1
+    steps:
+      # Checkout code from git
+      - checkout
+      - run:
+          name: Run migrations
+          command: |
+            cd backend
+            npm install
+            npm run migrations > migrations_dump.txt
+          #  exit 1
+      - run:
+          name: Send migration results to memstash
+          command: |
+            if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
+            then
+                curl https://kvdb.io/FS3hVsEzwoNt2BqndJbxfb/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
+            fi
+          # 
+          #  exit 1
+     # Here's where you will add some code to rollback on failure 
+      - destroy-environment:
+          stackname: "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}"
+      - destroy-environment:
+          stackname: "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}"
+  deploy-frontend:
+    docker:
+      - image: amazon/aws-cli
+    steps:
+      # Checkout code from git
+      - checkout
+      - attach_workspace:
+          at: .      
+      - run:
+          name: Install dependencies  tar gzip
+          command: |
+            yum install -y tar gzip
+      - run:
+          name: Install dependencies nodejs
+          command: |
+            yum -y install nodejs
+      - run:
+          name: Install dependencies awscli
+          command: |
+            yum -y install awscli
+      - run:
+          name: Install dependencies python3
+          command: |
+            yum -y install python3
+      - run:
+          name: Install dependencies npm
+          command: |
+            npm install
+            npm run build
+      - run:
+          name: Install dependencies ansible
+          command: |
+            apk add --update ansible
+
+      - run:
+          name: Get backend url
+          command: |
+            export BACKEND_IP=$(aws ec2 describe-instances \
+              --query 'Reservations[*].Instances[*].PublicIpAddress'
+              --output text)
+            export API_URL="http://${BACKEND_IP}:3030" 
+            echo "API_URL = ${API_URL}"
+            echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
+            cat frontend/.env
+      - run:
+          name: Deploy frontend objects
+          command: |
+            cd frontend
+            npm install
+            npm run build
+            tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz dist
+            aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
+
+      # Here's where you will add some code to rollback on failure 
+      - destroy-environment:
+          stackname: "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}"
+      - destroy-environment:
+          stackname: "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}"
 
 workflows:
   default:
@@ -201,3 +292,7 @@ workflows:
           requires: [test-frontend, test-backend, scan-frontend, scan-backend]
       - configure-infrastructure:
           requires: [deploy-infrastructure]
+      - run-migrations:
+          requires: [configure-infrastructure]
+      - deploy-frontend:
+          requires: [run-migrations]
